include(InstallRequiredSystemLibraries)
set(CPACK_PACKAGE_NAME "rk2")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_CONTACT "nadushka-23")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Chain of responsibility pattern example")
set(CPACK_DEBIAN_PACKAGE_NAME "rk2-chain")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_GENERATOR "DEB")
include(CPack)
