name: GTest CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -B build -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run Google Tests
        run: ./build/check
