name: Relise

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Package
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.deb
